13 app + generar usuario
ElOsoAstral/python-escomio pull request #14
Opened 2024-03-23 03:00 UTC by ElOsoAstral

Se agrego el método sing-up para crear un usuario.
Retorna un inicio de sesión

2024-03-23 23:59 UTC, BrianArz requested changes

2024-03-23 23:59 UTC, BrianArz commented on app/route/auth.py
Todo parece estar bien, pero por qué un código 201 y no 200?

2024-03-24 16:44 UTC, ElOsoAstral commented on app/route/auth.py
Fue un error que se me pasó al escribir, tienes razon debería ser 200

2024-03-24 18:54 UTC, BrianArz approved these changes

2024-03-24 18:54 UTC, merged